taipei-doit/Taipei-City-Dashboard

.github/ISSUE_TEMPLATE/new_component.md
=> Update issue template

index.html, package-lock.json, package.json, src/assets/styles/globalStyles.css, src/components/NavBar.vue, src/components/dialogs/MoreInfo.vue, src/components/dialogs/ReportIssue.vue, vite.config.js
**Issue:** N/A (Maintainer Push)
Prepared the project to deploy to the official environment.
-   [x] The pull …
=> Transition repository settings

.gitignore, package.json, public/dashboards/all_components.json, src/components/NavBar.vue, src/components/SideBar.vue, src/components/components/ComponentContainer.vue, src/components/components/ComponentMapChart.vue, src/components/dialogs/MoreInfo.vue, src/components/dialogs/NotificationBar.vue, src/components/utilities/ComponentTag.vue
**Issue:** Maintainer Commits
Conducted UX trials and modified the project according to the results. Also added mapData as a compressed directory for easier access for contributors.
- …
=> Revised Several UI Elements & Add mapData.tar.gz

index.html, src/assets/styles/toggleswitch.css, src/components/components/ComponentMapChart.vue, src/components/dialogs/InitialWarning.vue, src/store/mapStore.js
**Issue:** #20 
Fix issue #20
-   [x] Bug Fix
-   [ ] New Feature (Application)
-   [x] The pull request only resolves the issue(s) mentioned and nothing more …
=> Disabled toggling while requests are in progress

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, package.json, src/assets/configs/mapbox/arcGradient.js, src/store/mapStore.js
**Issue:** #22 
Added new arc map feature.
-   [ ] New Feature (Application)
-   [x] New Feature (Chart / Map Type)
-   [x] The pull request only resolves the issue(s) mentioned and …
=> Added Arc Map Functionality

public/dashboards/all_components.json
**Issue:** closes #42 
-   [x] Bug Fix
-   [ ] New Feature (Application)
-   [x] The pull request only resolves the issue(s) mentioned and nothing more
Thanks …
=> Removed Sensitive Data From "dispatch" Component

src/components/components/ComponentMapChart.vue, src/store/mapStore.js, src/views/MapView.vue
**Issue:** closes #50
-   [x] The pull request only resolves the issue(s) mentioned and nothing more
Thanks for …
=> [Enhancement] Add more info to mapview

public/dashboards/all_components.json
-   [ ] New Feature (Application)
-   [ ] Code linter has been run and issues have all been resolved
-   [ ] The code has been thoroughly tested and no visible bugs have been introduced
-   [ ] The pull request will completely resolve the issue(s) mentioned …
=> Clean all geojsons

src/assets/styles/globalStyles.css, src/components/charts/MapLegend.vue, src/components/components/ComponentContainer.vue, src/components/components/ComponentMapChart.vue, src/components/utilities/ComponentTag.vue
**Issue:** Closes #54 
- Increased font-m to 18px
- Highlighted active chart button
- Adjusted MapLegend Chart to less resemble buttons.
-   [x] The pull request will completely …
=> UI enhancements before taipei codefest

src/components/components/ComponentContainer.vue, src/components/components/ComponentMapChart.vue, src/components/utilities/ComponentTag.vue, src/components/utilities/TagTooltip.vue
**Issue:** #81 
-   [x] The pull request only resolves the issue(s) mentioned and nothing more
Thanks for your …
=> Added Tag Tooltip

public/dashboards/all_components.json
Improve the visuals of community-contributed components.
-   [x] The pull request only resolves the issue(s) …
=> Change dashboard colors

Taipei-City-Dashboard-BE/global/consts.go, Taipei-City-Dashboard-BE/internal/app/controllers/dashboard.go, Taipei-City-Dashboard-BE/internal/app/controllers/user.go, Taipei-City-Dashboard-BE/internal/app/middleware/common.go, Taipei-City-Dashboard-BE/internal/app/routes/router.go, Taipei-City-Dashboard-FE/index.html, Taipei-City-Dashboard-FE/src/components/dialogs/LogIn.vue, Taipei-City-Dashboard-FE/src/components/dialogs/UserSettings.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminEditIssue.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminEditUser.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/AdminSideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/router/axios.js, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/authStore.js, Taipei-City-Dashboard-FE/src/store/dialogStore.js, Taipei-City-Dashboard-FE/src/views/admin/AdminIssue.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminOverview.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminUser.vue
This repository is still under internal development. All outside pull requests will be closed immediately.
**Issue:** closes #130 
Per issue, created 4 APIs to handle user settings. Also created related FE pages to use the aforementioned APIs.
N/A
=> User related apis minor debugging

Taipei-City-Dashboard-FE/src/assets/configs/AllTimes.js, Taipei-City-Dashboard-FE/src/components/charts/ColumnLineChart.vue, Taipei-City-Dashboard-FE/src/components/charts/GuageChart.vue, Taipei-City-Dashboard-FE/src/components/charts/HistoryChart.vue, Taipei-City-Dashboard-FE/src/components/charts/TimelineSeparateChart.vue, Taipei-City-Dashboard-FE/src/components/charts/TimelineStackedChart.vue, Taipei-City-Dashboard-FE/src/components/components/ComponentContainer.vue, Taipei-City-Dashboard-FE/src/components/components/ComponentMapChart.vue, Taipei-City-Dashboard-FE/src/components/components/ComponentPreview.vue, Taipei-City-Dashboard-FE/src/store/authStore.js
This repository is still under internal development. All outside pull requests will be closed immediately.
- Fixed Component Info Page (Mobile) Bug where "資訊頁面" link doesn't disappear
- Fixed Timezone Bug where line charts automatically convert UTC+8 to UTC
- Added Maintenance Mode for components that are broken
N/A
=> Fixed Component Info, Timezone, Maintain Bug

Taipei-City-Dashboard-FE/package-lock.json, Taipei-City-Dashboard-FE/package.json, Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/ReportIssue.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminAddComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/main.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/admin/AdminEditComponent.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminIssue.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminUser.vue
This repository is still under internal development. All outside pull requests will be closed immediately.
Fixed the following bugs
- Word limit for components / issues
- Select options bg is white in windows but should be black
- When creating a new dashboard should redirect to the new dashboard but doesn't
- Cannot access the menu when username is too short
- Favorite and unfavorite needs debounce to prevent DDOS
- Add components dialog will be empty if add a component then reopen the dialog
N/A
=> Fixed Numerous FE Bugs [deploy debug 1]

docker/.env.template, docker/docker-compose-init.yaml
**Issue:** closes #154 
add MANAGER_SAMPLE_FILE & DASHBOARD_SAMPLE_FILE env default value
N/A
=> add default value

Taipei-City-Dashboard-FE/src/assets/configs/mapbox/mapConfig.js, Taipei-City-Dashboard-FE/src/components/map/MapContainer.vue, Taipei-City-Dashboard-FE/src/store/mapStore.js
Add district and village boundaries option to map.
N/A
=> Add default district and village boundaries

Taipei-City-Dashboard-FE/src/App.vue, Taipei-City-Dashboard-FE/src/components/components/ComponentContainer.vue, Taipei-City-Dashboard-FE/src/components/dialogs/EmbedComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/dialogStore.js, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/EmbedView.vue
=> Added Component Embedding Feature

Taipei-City-Dashboard-FE/src/components/utilities/bars/ComponentSideBar.vue, Taipei-City-Dashboard-FE/src/router/axios.js
- Fixed component sidebar bug where after the 6th component is added, the interface breaks.
- Fixed 403 notification bug when the user is logging out.
N/A
=> Fix add component sidebar bug

Taipei-City-Dashboard-FE/src/components/dialogs/ContributorsList.vue
=> Minor Contributors Dialog Fix

Taipei-City-Dashboard-FE/src/assets/utilityFunctions/calculateHaversineDistance.js, Taipei-City-Dashboard-FE/src/store/mapStore.js
- set up utils for getting the user's geolocation in mapStore
- prepare for finding the closest point to the user by relative distance
=> set up utils for getting the user's geolocation in mapStore

Taipei-City-Dashboard-FE/public/mapData/cctv.geojson, Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue
add new features (hackerdog - cctv)
--
=> feat: add hackerdog new features cctv

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: fix animate arc logic

.github/ISSUE_TEMPLATE/de_feature_request
**Issue:** #204 
Add `de_feature_request.md` to `.github/ISSUE_TEMPLATE/`
NA
=> Add data-end-issue template

Taipei-City-Dashboard-BE/cloudbuild.yaml, Taipei-City-Dashboard-FE/cloudbuild.yaml, Taipei-City-Dashboard-FE/index.html
1. Refactored to use GCP Secrets for sensitive data
2. Ensure that the VITE_APP_VERSION variable is properly substituted with the correct version information.
=> Refactored to use GCP Secrets for sensitive data

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0019/R0019.py
=> 修改: 連結更新:https://data.gov.tw/dataset/167441

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0035/R0035.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0035/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0035_hourly_calculate/R0035_hourly_calculate.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0035_hourly_calculate/job_config.json
=> 修改: 新增即時雨量與水位監控資料流

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0061/R0061.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0061/job_config.json
=> 修改:  更改符合前端geoserver table name

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0047/R0047.py
=> 修改: 歷史表欄位修正

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0087/R0087.py
=> 修改: 欄位錯誤修正

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0051_4/R0051_4.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0051_4/job_config.json
=> 新增: Youbike站點即時使用及剩餘量

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0051_4/R0051_4.py
=> 修改: 修正使用錯誤的欄位

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0051_4/R0051_4.py
=> 修改: 欄位使用錯誤

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0051_4/R0051_4.py
=> 修改: 修改欄位命名

Taipei-City-Dashboard-DE/cicd/utils/requirements.txt
=> 修改: 安裝必要套件

Taipei-City-Dashboard-DE/cicd/add-dags-to-composer.cloudbuild.yaml
=> CI: 移除--user 避免權限問題

Taipei-City-Dashboard-DE/cicd/add-dags-to-composer.cloudbuild.yaml
=> 修改: pip install 異常

Taipei-City-Dashboard-DE/cicd/utils/requirements.txt
=> 修改: 未知版本問題造成cloud build 無法正常執行

Taipei-City-Dashboard-DE/cicd/utils/requirements.txt
=> 修改: 添加google 套件

Taipei-City-Dashboard-DE/cicd/add-dags-to-composer.cloudbuild.yaml, Taipei-City-Dashboard-DE/cicd/utils/requirements.txt
=> 修改: 未知問題待解

Taipei-City-Dashboard-BE/app/controllers/isso.go
=> 修改: 測試isso

Taipei-City-Dashboard-BE/app/controllers/isso.go, Taipei-City-Dashboard-BE/global/global.go
=> 修改: 添加測試代碼

Taipei-City-Dashboard-BE/app/controllers/componentData.go, Taipei-City-Dashboard-BE/app/middleware/common.go, Taipei-City-Dashboard-BE/app/util/common.go
=> 修改: 調整錯誤的import

Taipei-City-Dashboard-BE/app/controllers/isso.go
=> 修改: 修改 print log

Taipei-City-Dashboard-BE/cloudbuild.yaml
=> 新增: cloudrun isso var

Taipei-City-Dashboard-FE/.env.template
=> 修改: template VITE_APP_TITLE 調整

Taipei-City-Dashboard-FE/src/assets/utilityFunctions/dataManager.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/interpolation.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/marchingSquare.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/voronoi.js, Taipei-City-Dashboard-FE/src/store/authStore.js, Taipei-City-Dashboard-FE/src/store/mapStore.js
=> 修改: 修正弱掃問題

Taipei-City-Dashboard-FE/src/assets/utilityFunctions/dataManager.js, Taipei-City-Dashboard-FE/src/components/dialogs/FindClosestPoint.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/router/axios.js, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/authStore.js, Taipei-City-Dashboard-FE/src/views/CallBack.vue, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue
=> 修改: 修正弱掃問題(改變數名稱)

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/v2/env_srv_energy_subsidy/env_srv_energy_subsidy.py
=> 修改:  更正dag_id

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/v2/env_srv_energy_subsidy/env_srv_energy_subsidy.py
=> 修改:  更正節能補助的RID

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0040/R0040.py
=> 修改: 刪除原始資料新增欄位positions_type

Taipei-City-Dashboard-BE/cloudbuild.yaml, Taipei-City-Dashboard-DE/cicd/add-dags-to-composer.cloudbuild.yaml
=> 修改: 加入加入logging

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/env_srv_energy_subsidy/env_srv_energy_subsidy.py
=> 修改:  加入臺北市服務業汰換節能設備補助相關資訊 更正

Taipei-City-Dashboard-DE/cicd/add-dags-to-composer.cloudbuild.yaml, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/env_srv_energy_subsidy/env_srv_energy_subsidy.py
=> 修改: 確認回傳資料 2

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/env_srv_energy_subsidy/env_srv_energy_subsidy.py
=> 修改:  將資料加入時區資訊

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/sea_sand_houses_tpe/sea_sand_houses_tpe.py
=> 修改: year處理方式錯誤

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/sea_sand_houses_tpe/job_config.json
=> 修改: load_behavior 僅接受append, replace, current+history

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/sea_sand_houses_tpe/job_config.json
=> 修改: 添加history 表

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/che_g2/che_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/che_g2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/che_g4/che_g4.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/che_g4/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/che_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/sea_sand_houses_tpe/job_config.json, Taipei-City-Dashboard-DE/dags/utils/auth_che.py
=> 新增: 串接信令資料,E2,G2,G4資料

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/che_e2.py, Taipei-City-Dashboard-DE/dags/utils/auth_che.py
=> 修改: variable參數

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py, Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: 添加debug code

Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: api return 欄位修正

Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: 移除expired_time

Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: 時間格式錯誤

Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: timeout時間為30分鐘

Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 修改: 錯誤參數引用

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 修改payload

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py
=> 修改: 測試測試user agent

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: header 加入uer-agent

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py
=> 修改: api帶入參數修正

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 轉df 參數錯誤

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 打平grids

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py
=> 修改: 將country 打平,以利後續操作

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py
=> 修改: 錯誤參數導致無法寫入db

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0022/R0022.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/youth_enterpreneurship_financing_loan_tpe/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/youth_enterpreneurship_financing_loan_tpe/youth_enterpreneurship_financing_loan_tpe.py, Taipei-City-Dashboard-DE/dags/utils/auth_cht.py
=> 新增: 添加資料流-臺北市青年創業融資貸款

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 添加大小巨蛋周邊網格資訊

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/cht_e2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/cht_g2.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 修正tabError 問題

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: 刪除錯誤column

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/cht_g4.py
=> 修改: lasttime_in_data 修正

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix/ location.origin set to citydashboard.taipei

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix/ citydashboard.taipei reset to location.origin

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/job_config.json
=> 修改: 暫時將執行時間改為一天執行一次

Taipei-City-Dashboard-FE/cloudbuild.yaml, Taipei-City-Dashboard-FE/src/App.vue
=> 新增: 支援個人儀表板更新頻率設定及地圖數據重載功能

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_e2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g2/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/cht_g4/job_config.json
=> 修改: 暫時調整為10分鐘更新

Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue
=> fix/ cctv source 用 iframe

Taipei-City-Dashboard-BE/cloudbuild.yaml, Taipei-City-Dashboard-FE/cloudbuild.yaml
=> 修改: 符合v3 cloud run

Taipei-City-Dashboard-BE/cloudbuild.yaml
=> 修改: 添加指定db name 參數

Taipei-City-Dashboard-FE/robots.txt
=> feat: add robots.txt to prevent search engine indexing in sit branch

Taipei-City-Dashboard-FE/vite.config.js
=> feat: add X-Robots-Tag header to prevent search engine indexing

Taipei-City-Dashboard-FE/index.html
=> feat: add googlebot meta tag to prevent search engine indexing

Taipei-City-Dashboard-BE/app/controllers/componentData.go, Taipei-City-Dashboard-BE/app/models/componentConfig.go, Taipei-City-Dashboard-BE/app/models/componentData.go, Taipei-City-Dashboard-BE/app/models/dashboard.go, Taipei-City-Dashboard-BE/app/routes/router.go
=> 新增: component 多城市

Taipei-City-Dashboard-BE/cloudbuild.yaml
=> 修改: 移除非必要參數

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/energy_saving_coaching_situation_tpe/energy_saving_coaching_situation_tpe.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/energy_saving_coaching_situation_tpe/job_config.json
=> 新增: 臺北市節能輔導情形資料流

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 新增: dashboard 回傳 public 向下相容

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> Refactor multiple cities

Taipei-City-Dashboard-FE/src/App.vue, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/dataManager.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/interpolation.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/marchingSquare.js, Taipei-City-Dashboard-FE/src/assets/utilityFunctions/voronoi.js, Taipei-City-Dashboard-FE/src/components/dialogs/FindClosestPoint.vue, Taipei-City-Dashboard-FE/src/components/dialogs/InitialWarning.vue, Taipei-City-Dashboard-FE/src/components/dialogs/LogIn.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/components/dialogs/ReportIssue.vue, Taipei-City-Dashboard-FE/src/components/dialogs/UserSettings.vue, Taipei-City-Dashboard-FE/src/components/map/MapContainer.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SettingsBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/SideBarTab.vue, Taipei-City-Dashboard-FE/src/router/axios.js, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/store/mapStore.js, Taipei-City-Dashboard-FE/src/store/personStore.js, Taipei-City-Dashboard-FE/src/views/CallBack.vue, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue
=> fix: 弱掃問題修正

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/energy_saving_coaching_situation_tpe_gov/energy_saving_coaching_situation_tpe_gov.py
=> 修改: 節能查核成效資料流

Taipei-City-Dashboard-BE/app/controllers/componentConfig.go, Taipei-City-Dashboard-BE/app/models/componentConfig.go, Taipei-City-Dashboard-BE/app/models/componentData.go, Taipei-City-Dashboard-BE/app/models/dashboard.go, Taipei-City-Dashboard-BE/app/routes/router.go
=> 新增: cityComponents

Taipei-City-Dashboard-BE/app/controllers/dashboard.go, Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 新增: get dashboard by index 可帶入 param city 修改: 未登入不回傳 personal dashboard

Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> feat: 新增 toggleOn 屬性以支援下拉選單切換縣市功能，並調整相關邏輯

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue
- 修復個人儀表板缺少 city 參數時的跳轉異常
- 新增手機版儀表板導航時的 city 參數傳遞
=> fix: city 參數導航問題

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
- code formatted
- unused param
=> fix: build error

Taipei-City-Dashboard-FE/src/store/contentStore.js
=> fix: 修正當前儀表板內容的查找邏輯，以支援城市過濾

Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/store/contentStore.js
=> feat: 各縣市儀表板的圖資資訊各自呈現

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminAddEditDashboards.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/AdminSideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/forms/InputTags.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/SideBarTab.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/MapView.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminDashboard.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminEditComponent.vue
=> feat: 更新管理員後台儀表板、優化各縣市設定與顯示

Taipei-City-Dashboard-BE/app/models/componentConfig.go
=> 修改: 修改db 結構

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 修改: 修正語法錯誤

Taipei-City-Dashboard-BE/app/controllers/dashboard.go, Taipei-City-Dashboard-BE/app/routes/router.go
=> 新增: admin 可新增 public taipei metrotaipei dashboard

Taipei-City-Dashboard-DE/dags/operators/common_pipeline.py
=> 修改: 修正錯誤存取dict方式

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 修改: 增加map_config city 欄位

Taipei-City-Dashboard-FE/src/assets/configs/apexcharts/chartTypes.js, Taipei-City-Dashboard-FE/src/dashboardComponent/components/TextUnitChart.vue
=> fix: TextUnitChart 用 three_d 的資料架構來呈現

Taipei-City-Dashboard-DE/dags/operators/common_pipeline.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/dependency_ratio_and_aging_index/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/ebus_base_info/ebus_base_info.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/employment_age_structure/employment_age_structure.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/employment_age_structure/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/population_age_distribution_monthly/population_age_distribution_monthly.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/dependency_ratio_and_aging_index/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/ebus_base_info/ebus_base_info.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/ebus_base_info/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/employment_age_structure/job_config.json
=> Refactor data streams tpe ntpc

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/ebus_base_info/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/ebus_base_info/job_config.json
=> 修改: 修正錯誤table name,與load_behavior

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/population_age_distribution_monthly/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/employment_age_structure/employment_age_structure.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/population_age_distribution_monthly/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/population_age_distribution_monthly/population_age_distribution_monthly.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/youbike_station_realtime_usage_and_availability/youbike_station_realtime_usage_and_availability.py
=> 修改: 修改錯誤dataframe 引用

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/ebus_base_info/ebus_base_info.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/ebus_base_info/ebus_base_info.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/youbike_station_realtime_usage_and_availability/youbike_station_realtime_usage_and_availability.py
=> 修改: 修改tdx requests

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/youbike_station_realtime_usage_and_availability/youbike_station_realtime_usage_and_availability.py
=> 修改: youbike tdx 與 taipei來源回傳資料不同,進行對齊作業

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/population_age_distribution_monthly/population_age_distribution_monthly.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/ebus_base_info/ebus_base_info.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/youbike_station_realtime_usage_and_availability/youbike_station_realtime_usage_and_availability.py
=> 修改: 欄位問題修正

Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminAddComponent.vue, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/store/mapStore.js, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/ComponentView.vue
=> fix: city參數處理與地圖圖層區分

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/employment_age_structure/employment_age_structure.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/population_age_distribution_monthly/population_age_distribution_monthly.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/youbike_station_realtime_usage_and_availability/youbike_station_realtime_usage_and_availability.py, Taipei-City-Dashboard-DE/dags/utils/extract_stage.py
=> 修改: 修正錯誤邏輯與ntpc 需要帶page與size 參數取得更多資料問題

Taipei-City-Dashboard-DE/dags/utils/extract_stage.py
=> 修改: page 必須從第0頁開始

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/employment_age_structure/employment_age_structure.py
=> 修改: 錯誤的語法造成dataframe被轉回list

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 修改: 修改 map_config city 的值

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py
=> 修改: 修正Geometry寫入問題

Taipei-City-Dashboard-BE/app/models/dashboard.go
=> 修改: fix error

Taipei-City-Dashboard-BE/cloudbuild.yaml
=> 修改: 添加cloud build 變數

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py
=> 修改: 刪除非必要欄位

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py
=> 修改: 移除非必要欄位

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py
=> 修改: 欄位有空直填入None

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/bike_path/bike_path.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/bike_path/bike_path.py
=> 修改: 移除非必要套件

Taipei-City-Dashboard-FE/src/dashboardComponent/components/DistrictChart.vue
=> fix: 行政區組件樣式

Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 更新 DashboardComponent 的map-layers 組件 key 屬性，並調整城市選單的禁用邏輯

Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue
=> fix: cctv的popup，根據來源選擇顯示圖片或iframe

Taipei-City-Dashboard-FE/src/components/dialogs/DownloadData.vue, Taipei-City-Dashboard-FE/src/components/dialogs/EmbedComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/router/index.js, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/EmbedView.vue
- 修正資訊頁面下載與內嵌彈窗的組件對應錯誤
- 改用 props 直接傳遞組件資訊
- 新增路由參數 city（/embed/:id/:city）以正確對應 EmbedView 組件
=> fix: 修正組件瀏覽平台組件對應問題、優化資訊傳遞並更新路由

Taipei-City-Dashboard-FE/src/store/contentStore.js
=> fix: 我的最愛跟個人儀表板只要有雙北組件，基本圖層統一使用雙北圖資

Taipei-City-Dashboard-FE/src/dashboardComponent/components/TextUnitChart.vue
- 因為 categories 中相同的值會被合併成一筆
- series 的 data 中 name 相同的項目也會被合併成一筆
=> fix: 修正 TextUnitChart 不使用 categories 做資料處理，改用icon欄位來做單位的顯示

Taipei-City-Dashboard-FE/src/dashboardComponent/components/TextUnitChart.vue
=> fix: 修正 TextUnitChart 組件中 props 的使用，確保顏色和單位顯示正確

Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue
=> fix: 調整儀表板控制按鈕的樣式與結構

Taipei-City-Dashboard-FE/src/store/adminStore.js
=> fix: 後台更新組件 API 請求路徑添加 city 參數

Taipei-City-Dashboard-BE/app/models/componentConfig.go
=> 修改: links contributor 沒資料問題

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_disaster_summary/eoc_disaster_summary.py
=> 修改: 原始資料多了一個欄位

Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
- 臺北儀表板的所有組件（含地圖交叉比對的基本圖層和圖資資訊map-layer）禁用城市切換
- 非臺北儀表板保留城市切換功能
- 城市選單拿掉change事件避免重複觸發
- 添加 try/catch 與 console.error 錯誤輸出
=> fix: 統一城市選單切換邏輯並增強錯誤處理

Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue
=> fix: 調整縱向長條圖的縮放選項並修改圖表高度

Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue, Taipei-City-Dashboard-FE/src/store/contentStore.js
=> fix: 優化儀表板組件資料獲取與顯示邏輯

Taipei-City-Dashboard-FE/src/App.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 修正顯示細節與樣式調整

Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/store/contentStore.js
- 增加預覽模式下顯示 city 名稱並調整樣式
- 修正組件過濾邏輯，確保不會過濾掉雙北的資料
=> fix: 優化預覽模式與資料過濾

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0047/job_config.json
=> 修改: 將捷運人流改為每30分鐘一次,取消夜間暫停排程。

Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/SideBarTab.vue
=> feat: 新增SideBar的摺疊功能與動畫效果

Taipei-City-Dashboard-FE/src/components/dialogs/LogIn.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue
- 調整 Logo 副標為 "City Dashboard"
- 優化城市選單：禁用狀態下使用客製化樣式顯示城市名稱
- 修正 sideBar 可滾動時的內容穿透問題
- 調整 dashBoardComponent 更新頻率標籤樣式：確保換行後的標籤與第一行文字對齊
- 限制後台編輯功能：禁止修改組件名稱
=> fix: UI 樣式優化與功能修正

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue
=> feat: MobileNavigation 選單儀表板摺疊功能與動畫效果

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue
=> feat: MobileNavigation 新增個人儀表板無內容提示與樣式調整

Taipei-City-Dashboard-FE/public/manifest.json, Taipei-City-Dashboard-FE/src/assets/styles/chartStyles.css, Taipei-City-Dashboard-FE/src/components/dialogs/InitialWarning.vue, Taipei-City-Dashboard-FE/src/components/dialogs/LogIn.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ComponentTag.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/GuageChart.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/styles/chartStyles.css, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> merge: UI 元件優化

Taipei-City-Dashboard-FE/src/assets/styles/chartStyles.css, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/GuageChart.vue
=> fix: 調整圖表樣式與寬度，修正 GuageChart 與 ColumnChart 的顯示效果

Taipei-City-Dashboard-BE/app/controllers/componentConfig.go, Taipei-City-Dashboard-BE/app/controllers/componentData.go, Taipei-City-Dashboard-BE/app/controllers/dashboard.go, Taipei-City-Dashboard-BE/app/routes/router.go
=> 修改: city parameter 參數

Taipei-City-Dashboard-FE/src/assets/styles/chartStyles.css, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/GuageChart.vue, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/EmbedView.vue
=> merge: 圖表顯示優化與 API 請求標準化

Taipei-City-Dashboard-FE/src/assets/styles/globalStyles.css, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/ComponentTag.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminEditComponent.vue
=> feat: 組件新增城市標籤tag顯示

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0022/R0022.py
=> 修改: 來源資料修改

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/R0022/R0022.py
=> 修改: 字串內包含空格需要去除

Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/store/adminStore.js
=> fix: 修正 adminStore API 路徑與 dashboardComponent 城市標籤邏輯

Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/styles/chartStyles.css, Taipei-City-Dashboard-FE/src/dashboardComponent/styles/toggleswitch.css, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/EmbedView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> refactor: 整合城市選單與標籤邏輯，設置 selectBtn 預設為關閉，map-layer 改用 includes 判斷

Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue
=> fix: 修正 API 路徑，更新歷史記錄請求，並處理可能的 undefined 錯誤

Taipei-City-Dashboard-FE/src/dashboardComponent/components/ColumnChart.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminDashboard.vue
=> fix: 調整 ColumnChart filter標籤超過12個項目時的位置，並為 AdminDashboard 增加 z-index 屬性

Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/DistrictChart.vue
=> fix: 將 "台北市" 的名稱修正為 "臺北市"

Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue
=> feat: 新增對 tdx.transportdata 的資料集連結判斷

Taipei-City-Dashboard-BE/app/controllers/componentConfig.go, Taipei-City-Dashboard-BE/app/models/componentConfig.go, Taipei-City-Dashboard-BE/app/routes/router.go
=> Add: return all components of an ID

db-sample-data/dashboardmanager-demo.sql
=> 修改: docker compose sql 資料

Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminAddComponent.vue, Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue, Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/AdminSideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/utilities/cityManager.ts, Taipei-City-Dashboard-FE/src/store/adminStore.js, Taipei-City-Dashboard-FE/src/store/authStore.js, Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/ComponentView.vue, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/EmbedView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue, Taipei-City-Dashboard-FE/src/views/admin/AdminDashboard.vue
=> feat: 支援透過配置方式設定儀表板選單、城市選單及城市標籤的顯示

Taipei-City-Dashboard-FE/vite.config.js
=> fix: 修改 vitConfig 使用 import.meta.env 讀取DOCKER_COMPOSE 環境變數

Taipei-City-Dashboard-FE/src/views/EmbedView.vue
=> fix: 修復 EmbedView 城市選單與城市標籤的顯示問題

Taipei-City-Dashboard-FE/vite.config.js
=> fix: 修改 vitConfig 使用 process 讀取DOCKER_COMPOSE 環境變數

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue
=> feat: 增加公共儀表板選單的折疊狀態初始化功能，並在城市變更時自動更新

Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue
=> fix: 在 ComponentInfoView 中新增城市標籤屬性以顯示城市相關標籤

Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/AdminSideBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/SideBar.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/utilities/cityManager.ts
=> fix: 更新導航選單城市名稱標題，新增擴展與收縮名稱屬性

Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 設置圖層資訊索引固定前綴為"map-layer-"，私人儀表板不包含基本圖層

Taipei-City-Dashboard-DE/dags/operators/common_pipeline.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/D020201/D020201.py
=> 修改: 原始欄位調整

Taipei-City-Dashboard-FE/src/views/ComponentInfoView.vue
=> fix: 修正組件瀏覽平台資訊頁面的樣式

Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 修正地圖交叉比對切換城市選單時 setComponentData 使用正確的 componentIndex

Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/DashboardView.vue
=> fix: 修正切換城市選單時 setComponentData 使用正確的 componentIndex，確保正確更新

Taipei-City-Dashboard-FE/src/store/contentStore.js, Taipei-City-Dashboard-FE/src/views/DashboardView.vue, Taipei-City-Dashboard-FE/src/views/MapView.vue
=> Merge: 修正切換城市選單時 setComponentData 使用正確的 componentIndex，確保正確更新

Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/MobileLayerTab.vue
=> fix: mobileLayerTab 文字顯示完整

Taipei-City-Dashboard-FE/src/components/dialogs/MobileLayers.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/MobileLayerTab.vue, Taipei-City-Dashboard-FE/src/router/index.js
=> fix: 手機版看地圖交叉比對

Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue
=> fix: 增加對 map_config 的安全檢查以避免ComponentTag顯示錯誤

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整欄位使用錯誤

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: delete 失敗可跳過

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> modify: script adjustment

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> modify: adjust script

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整index

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 已存在的dashboard就不在建立, 跳過

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: geo_server use location.origin

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: geo_server使用location.origin並移除未使用程式碼

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整刪除功能

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 依照components id 刪除dashboard

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 預設添加最新災情組件

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整取得id方式

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: type調整

Taipei-City-Dashboard-FE/src/assets/styles/toggleswitch.css, Taipei-City-Dashboard-FE/src/dashboardComponent/styles/toggleswitch.css
=> fix: 為 toggleSwitchBtn 的 overflow 屬性添加 !important 以防止被全局樣式覆蓋

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: 移除地圖可視區域範圍限制以改善圖層加載

Taipei-City-Dashboard-FE/src/assets/styles/toggleswitch.css, Taipei-City-Dashboard-FE/src/dashboardComponent/DashboardComponent.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/styles/toggleswitch.css, Taipei-City-Dashboard-FE/src/store/mapStore.js
- 移除地圖可視區域範圍限制以改善圖層加載
- 為 toggleSwitchBtn 的 overflow 屬性添加 !important 以防止被全局樣式覆蓋
- 增加對 map_config 的安全檢查以避免 ComponentTag 顯示錯誤
=> fix: 綜合相關問題修復

Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 修正個人儀表板地圖交叉比對下拉選單無法正常顯示的問題

Taipei-City-Dashboard-FE/src/views/MapView.vue
=> fix: 修正個人儀表板地圖交叉比對，空間資料組件下拉選單應依組件所屬城市顯示、單一城市不顯示選單

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/district_population_household_tpe/district_population_household_tpe.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/district_population_household_tpe/job_config.json
=> 新增: 各行政區人口統計資料流

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/district_population_household_tpe/district_population_household_tpe.py
=> 修改: 各行政區人口統計資料流

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/li_age_population_tpe/li_age_population_tpe.py
=> 新增: 各里人口統計資料流

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/li_age_population_tpe/li_age_population_tpe.py
=> 修改: 調整篩選條件

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/friendly_store/friendly_store.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/friendly_store/job_config.json
=> 新增: 友善店家清單組件

Taipei-City-Dashboard-FE/src/assets/configs/mapbox/mapConfig.js, Taipei-City-Dashboard-FE/src/components/dialogs/MobileLayers.vue, Taipei-City-Dashboard-FE/src/components/dialogs/MobileNavigation.vue, Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/MobileLayerTab.vue, Taipei-City-Dashboard-FE/src/router/index.js
=> Merge 看地圖交叉比對 ＆ 更新臺北地圖的中心點和縮放級別

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> Merge codefest 2025: enhance map layers with metro isoline and animated hazard water

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/aed_locations/job_config.json
=> 修改: aed config

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/friendly_store/job_config.json
=> 修改: 友善店家 config

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> test: 測試改檔案名稱

Taipei-City-Dashboard-FE/nginx.conf
=> test: 測試修改nginx.conf 看檔不能解決geojson 檔案太大的問題

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/youth_enterpreneurship_financing_loan_tpe/youth_enterpreneurship_financing_loan_tpe.py
=> 修改: 鎖定欄位,避免寫入異常

Taipei-City-Dashboard-FE/nginx.conf, Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: 還原測試內容

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/aed_locations/aed_locations.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/aed_locations/job_config.json
=> 修改: 增加新北aed

Taipei-City-Dashboard-FE/src/dashboardComponent/components/DistrictChart.vue
=> feat: codefest 2025 行政區 tooltip 優化

Taipei-City-Dashboard-DE/dags/utils/transform_address.py
=> 修改: 使用proxy

Taipei-City-Dashboard-DE/dags/utils/transform_address.py
=> 修改: 調整variable get 內容

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/tourist_attractions/tourist_attractions.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/tourist_attractions/tourist_attractions.py, Taipei-City-Dashboard-DE/dags/utils/extract_stage.py
=> 2025 hackathon/merge no 1

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/accessible_facilities/accessible_facilities.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/general_hotel_registry/general_hotel_registry.py
=> 新增台北市停車場與市場無障礙設施資料

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/tourist_attractions/tourist_attractions.py
=> 修改: 缺少datatime

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_damage_case/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_disaster_summary/job_config.json
=> 寫入改為current+history

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/elderly_clud/elderly_club.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/elderly_clud/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/elderly_club/job_config.json
=> 修改: 調整錯誤內容

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/rainfall_flood_simulation_etl/job_config.json, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/rainfall_flood_simulation_etl/job_config.json
=> 修改: schedule_interval 解析異常,可能是版本問題

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/yearly_death_cause_etl/yearly_death_cause_etl.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/yearly_death_cause_etl/yearly_death_cause_etl.py
=> modify: wrong variable

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/flu_hospitals_tpe/flu_hospitals_tpe.py, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/flu_hospitals_tpe/job_config.json, Taipei-City-Dashboard-DE/dags/proj_city_dashboard/yearly_death_cause_etl/yearly_death_cause_etl.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/flu_hospitals_ntpe/flu_hospitals_ntpe.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/flu_hospitals_ntpe/job_config.json
=> 2025 hackathon/merge no 4

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/flu_hospitals_tpe/flu_hospitals_tpe.py, Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/flu_hospitals_ntpe/flu_hospitals_ntpe.py
=> modify variable

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> component modify

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/general_hotel_registry/general_hotel_registry.py
=> 修改: 欄位rename 錯誤

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/general_hotel_registry/general_hotel_registry.py
=> 修改: 錯誤欄位調整

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/aed_locations/aed_locations.py
=> 修改: 確認哪個值有問題

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/aed_locations/aed_locations.py
=> 修改: 全部打開,確認哪筆有問題

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> Modify eoc

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整eoc 組件

Taipei-City-Dashboard-FE/package-lock.json, Taipei-City-Dashboard-FE/package.json, Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue, Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: 新增 HLS.js 處理 cctv 的 m3u8格式串流

Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: remove console

Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue, Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: 影像串流跨域問題(測試)

Taipei-City-Dashboard-FE/src/components/map/MapPopup.vue, Taipei-City-Dashboard-FE/src/store/mapStore.js
=> fix: 刪掉測試內容

Taipei-City-Dashboard-FE/src/components/dialogs/DownloadData.vue, Taipei-City-Dashboard-FE/vite.config.js
=> fix: add debug log for CSV string and enable sourcemaps in build config

Taipei-City-Dashboard-FE/src/components/dialogs/DownloadData.vue
=> fix: test CSV encoding

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/accessible_facilities/accessible_facilities.py
=> 合併2025年黑客松第一名(亂寫都對)組件

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/accessible_facilities/accessible_facilities.py
=> 修改: 錯誤內容修正

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/accessible_facilities/accessible_facilities.py
=> 修改: 欄位使用錯誤修正

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/dependency_ratio_and_aging_index/dependency_ratio_and_aging_index.py
=> 修改: 因資料源問題導致不需要drop欄位消失

Taipei-City-Dashboard-FE/src/components/dialogs/MobileLayers.vue, Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/MobileLayerTab.vue, Taipei-City-Dashboard-FE/src/dashboardComponent/components/DistrictChart.vue, Taipei-City-Dashboard-FE/src/store/mapStore.js, Taipei-City-Dashboard-FE/src/views/MapView.vue, Taipei-City-Dashboard-FE/vite.config.js
=> Merge: 手機版地圖交叉比對，雙北儀表板可切換城市顯示圖層

Taipei-City-Dashboard-DE/dags/proj_city_dashboard/eoc_dashboard_controller/eoc_dashboard_controller.py
=> 修改: 調整insert參數

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/fire_narrow_street/fire_narrow_street.py
=> 修改: 必須到號才可以

Taipei-City-Dashboard-DE/dags/proj_new_taipei_city_dashboard/fire_narrow_street/fire_narrow_street.py
=> 修改: 會有無法寫入點位問題

.github/workflows/build-and-push.yml
=> Add kubeconfig debugging for both backend and frontend jobs

helm-chart/templates/backend-deployment.yaml, helm-chart/templates/frontend-deployment.yaml
- Fix missing {{- end }} statements in frontend-deployment.yaml
- Remove Azure Key Vault volume mounts and references
- Clean up broken template syntax from automated processing
- Ensure proper YAML structure for both frontend and backend deployments
- Remove references to deleted secret-provider-class.yaml
- Templates now parse successfully with helm template command
=> Fix YAML syntax errors in deployment templates
